version: "3.9" 
services:
  # comm:
  #   image: amyangxyz111/rethi-comm
  #   ports:
  #     - "8000:8000"
  #     - "10000-10007:10000-10007/udp" # listening ports
  #   depends_on:
  #     - db
  #   links:
  #     - db
  
  data_service:
    image: data_service
    environment: # should be same with db's env
      DB_NAME: hms
      DB_USER: uu
      DB_PASSWORD: password
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb 
    environment:
      MYSQL_ROOT_PASSWORD: any
      MYSQL_DATABASE: hms
      MYSQL_USER: uu
      MYSQL_PASSWORD: password
    expose:
      - "3306"