version: "3.9"
services:
  comm:
    image: amyangxyz111/rethi-comm
    # image: comm-t
    environment:
      ADDR_LOCAL_GCC: ":10000"
      ADDR_LOCAL_HMS: ":10001"
      ADDR_LOCAL_STR: ":10002"
      ADDR_LOCAL_PWR: ":10003"
      ADDR_LOCAL_ECLSS: ":10004"
      ADDR_LOCAL_AGT: ":10005"
      ADDR_LOCAL_INT: ":10006"
      ADDR_LOCAL_EXT: ":10007"
      ADDR_REMOTE_GCC: "host.docker.internal:20000" # refer to host's localhost
      ADDR_REMOTE_HMS: "host.docker.internal:20001"
      ADDR_REMOTE_STR: "host.docker.internal:20002"
      ADDR_REMOTE_PWR: "host.docker.internal:20003"
      ADDR_REMOTE_ECLSS: "host.docker.internal:20004"
      ADDR_REMOTE_AGT: "host.docker.internal:20005"
      ADDR_REMOTE_INT: "host.docker.internal:20006"
      ADDR_REMOTE_EXT: "host.docker.internal:20007"
      DB_DB: comm
      DB_USER: uu
      DB_PASSWORD: password
    ports:
      - "8000:8000"
      - "10000-10007:10000-10007/udp"
    depends_on:
      - comm_db
    links:
      - comm_db

  comm_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: comm
      MYSQL_USER: uu
      MYSQL_PASSWORD: password
    expose:
      - "3306"

  data_service:
    image: data-service
    ports:
      - "20001:20001"
    environment:
      DB_DB: hms
      DB_USER: uu
      DB_PASSWORD: password
    depends_on:
      - hms_db
    links:
      - hms_db

  hms_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: hms
      MYSQL_USER: uu
      MYSQL_PASSWORD: password
    expose:
      - "3306"
