version: "3.9"
services:
  comm:
    image: amyangxyz111/rethi-comm
    environment:
      ADDR_LOCAL_GCC: ":10000"
      ADDR_LOCAL_HMS: ":10001"
      ADDR_LOCAL_STR: ":10002"
      ADDR_LOCAL_SPL: ":10011"
      ADDR_LOCAL_PWR: ":10003"
      ADDR_LOCAL_ECLSS: ":10005"
      ADDR_LOCAL_AGT: ":10006"
      ADDR_LOCAL_EXT: ":10007"
      ADDR_LOCAL_IE: ":10008"
      ADDR_LOCAL_DTB: ":10009"
      ADDR_LOCAL_COORD: ":10010"

      ADDR_REMOTE_GCC: "host.docker.internal:20000" #
      ADDR_REMOTE_HMS: "host.docker.internal:20001"
      ADDR_REMOTE_STR: "host.docker.internal:20002"
      ADDR_REMOTE_SPL: "host.docker.internal:20011"
      ADDR_REMOTE_PWR: "host.docker.internal:20003"
      ADDR_REMOTE_ECLSS: "host.docker.internal:20005"
      ADDR_REMOTE_AGT: "host.docker.internal:20006"
      ADDR_REMOTE_EXT: "host.docker.internal:20007"
      ADDR_REMOTE_IE: "host.docker.internal:20008"
      ADDR_REMOTE_DTB: "host.docker.internal:20009"
      ADDR_REMOTE_COORD: "host.docker.internal:20010"

      CONSOLE_ENABLED: "true"
      DELAY_ENABLED: "false"
      FRER_ENABLED: "false"
      RAND_SEED: "123"
      JITTER: "10"
      DB_DB: comm
      DB_USER: uu
      DB_PASSWORD: password
    ports:
      - "8000:8000"
      - "10000-10010:10000-10010/udp"
    depends_on:
      - comm_db
    networks:
      - hms-network
      - comm-network

  comm_db:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: comm
      MYSQL_USER: uu
      MYSQL_PASSWORD: password
    expose:
      - "3306"
    networks:
      - comm-network

networks:
  comm-network: null
  hms-network: null
  